Update README.md
after performing steps mentioned until 3 then we need to do following steps before performing step-4
library(reticulate)
py_install('aif360')

This steps needs to be performed otherwise following error will be thrown:
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'aif360'